services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/caddy/certs:/etc/caddy/certs:ro
      - caddy-data:/data
      - /var/lib/caddy/acme:/var/lib/caddy/acme
      - caddy-config:/config
    networks:
      - caddy-net

networks:
  caddy-net:
    external: true

volumes:
  caddy-data:
  caddy-config:
